use_frameworks!

platform :ios, '9.0'

target 'LGDLogining_Example' do
  pod 'LGDLogining', :path => '../'

  target 'LGDLogining_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
